.ssh-prep-before_script: &ssh-prep-before_script |
  apt-get update && apt-get install -y --no-install-recommends libssl-dev git openssh-server

.python-prep: &python-prep |
  apt-get update && apt-get install -y --no-install-recommends build-essential stress libglib2.0-0 libgl1 python3.10-dev python3-pip
  ln -s /usr/bin/python3 /usr/bin/python && rm /usr/bin/pip && ln -s /usr/bin/pip3 /usr/bin/pip && pip install -U pip

.default-rules: &default-rules
  - if: $CI_COMMIT_REF_NAME == "master"
  - if: $CI_PIPELINE_SOURCE == "web"
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.default_python_unittest:
  image: gitlab.ordulu.com:5050/ai-team/build-systems/ai-core:latest
  script:
    - pip install --ignore-installed -r requirements.txt
    - python -m unittest
  rules:
    - *default-rules

.default_pre_commit:
  image: gitlab.ordulu.com:5050/ai-team/build-systems/ai-core:latest
  script:
    - pip install pre-commit
    - pre-commit run --all-files
  rules:
    - *default-rules

stages:
  - pre_commit
  - test

pre_commit:
  stage: pre_commit
  extends: .default_pre_commit

test:
  stage: test
  extends: .default_python_unittest
