repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: debug-statements
      - id: name-tests-test
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: destroyed-symlinks
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        exclude: ^(^pre_commit/resources/|testing/resources/python3_hooks_repo/|^train_app/version.py)
        args: [--py38-plus, --add-import, "from __future__ import annotations"]
  # - repo: https://github.com/asottile/add-trailing-comma
  #   rev: v2.4.0
  #   hooks:
  #     - id: add-trailing-comma
  #       args: [--py36-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        args: [--in-place, --ignore, E203, --max-line-length, "150"]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=150]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
  - repo: https://github.com/psf/black.git
    rev: 23.1.0
    hooks:
      - id: black
        args: [--line-length=150]
